print """# This file is autogenerated by irq.s_generator.py
# DO NOT EDIT IT MANUALLY!\n\n"""

for i in range(0,16):
	print ".global irq"+str(i)
	print "irq"+str(i)+":"
	print "\tcli"
	print "\tpush $0" # Push a dummy error code
	print "\tpush $"+str(i+32)
	print "\tjmp irq_common_stub"
	print

print """.extern irq_handler
irq_common_stub: 
	pusha
	push %ds
	push %es
	push %fs
	push %gs
	movw $0x10,%ax
	movw %ax,%ds
	movw %ax,%es
	movw %ax,%fs
	movw %ax,%gs
	movl %esp,%eax
	pushl %eax
	movl $irq_handler, %eax
	call *%eax
	popl %eax
	popl %gs
	popl %fs
	popl %es
	popl %ds
	popa
	addl $8,%esp
	iret"""
