exceptions=[
["Division By Zero", False],
["Debug", False],
["Non Maskable Interrupt", False],
["Breakpoint", False],
["Into Detected Overflow", False],
["Out of Bounds", False],
["Invalid Opcode", False],
["No Coprocessor", False],
["Double Fault", True],
["Coprocessor Segment Overrun", False],
["Bad TSS", True],
["Segment Not Present", True],
["Stack Fault", True],
["General Protection Fault", True],
["Page Fault", True],
["Unknown Interrupt", False],
["Coprocessor Fault", False],
["Alignment Check Exception (486+)", False],
["Machine Check Exception (Pentium/586+)", False],
["Reserved", False],
["Reserved", False],
["Reserved", False],
["Reserved", False],
["Reserved", False],
["Reserved", False],
["Reserved", False],
["Reserved", False],
["Reserved", False],
["Reserved", False],
["Reserved", False],
["Reserved", False],
["Reserved", False]]
